'use strict';
const assert=require('assert'),cfg=require('../core/config'),Game=require('../core/game'),Adventure=require('../core/adventure');
const deps={World:require('../core/world'),Entities:require('../core/entities'),Progression:require('../core/progression'),Save:require('../core/save')};
function make(){const values={},account={data:{playerId:1},ready:true,queue:p=>account.latest=p,sync:()=>{},message:''};const g=new Game(cfg,{...deps,storage:{get:k=>values[k],set:(k,v)=>{values[k]=v;return true;}}});g.setViewport(812,375);const a=new Adventure(g,account,{getStorageSync:k=>values[k],setStorageSync:(k,v)=>values[k]=v});a.storySeen=true;a.enterChapter(false);return {g,a,account,values};}
let s=make();const before=s.g.masteryOf();s.g.stageClear();assert(s.a.victory);assert(s.g.trial.finished);assert.equal(s.account.latest.chapterCompleted,1);assert(!s.g.loadMeta().run,'completed run cannot be resumed for rewards');const earned=s.g.masteryOf();assert(earned>before);s.g.stageClear();assert.equal(s.g.masteryOf(),earned,'settlement is idempotent');
const elapsed=s.g.elapsed,hp=s.g.player.hp;s.a.update(.3,{moveX:1,tap:{x:200,y:100}});assert.equal(s.g.elapsed,elapsed);assert.equal(s.g.player.hp,hp);assert.equal(s.g.bgmTrack(),null);
s.g.pause();const age=s.a.victory.age;s.a.update(.5,{});assert.equal(s.a.victory.age,age,'background pause freezes cinematic');s.g.resume();for(let i=0;i<60;i++)s.a.update(.1,{});assert(s.a.dialogue);assert.equal(s.a.dialogue.lines.length,5);
while(s.a.dialogue){s.a.guard=0;s.a.update(.1,{tap:{x:20,y:20}});}assert.equal(s.g.state,'clear');s.a.update(.7,{});s.a.update(.1,{tap:{x:10,y:10}});assert.equal(s.a.mode,'chapters');assert(s.a.layout().buttons.find(b=>b.id==='start').label.includes('已通关'));
s.a.guard=0;const library=s.a.layout().buttons.find(b=>b.id==='library');s.a.update(.1,{tap:{x:library.x+3,y:library.y+3}});assert.equal(s.a.mode,'library');const oldWeapon=s.g.weaponKind(),r=s.g.codexRects();s.a.update(.1,{tap:{x:r.tabs[1].x+2,y:r.tabs[1].y+2}});assert.equal(s.g.weaponKind(),oldWeapon,'home library is read-only');s.a.update(.1,{tap:{x:r.back.x+2,y:r.back.y+2}});assert.equal(s.a.mode,'chapters');
s.a.enterChapter(false);s.g.stageClear();for(let i=0;i<60;i++)s.a.update(.1,{});assert.equal(s.g.state,'clear');assert(!s.a.dialogue,'repeat clear skips long epilogue');
// Dash pressed against an impassable surface must not count as a completed movement.
s=make();s.a.startTutorial();s.a.dialogue=null;s.a.setupStep(3);s.g.update=function(dt,input){this.player.dash=input.dash?.1:Math.max(0,this.player.dash-dt);};s.a.update(.04,{dash:true});s.a.update(.2,{});assert(!s.a.success);s.g.update=function(dt,input){this.player.dash=input.dash?.1:Math.max(0,this.player.dash-dt);this.player.x+=20;};s.a.update(.04,{dash:true});assert(!s.a.success);s.a.update(.2,{});assert(s.a.success);
console.log('Victory: settle before presentation, no duplicate rewards, pause, first/repeat clear, home library and dash displacement passed.');
