const assert=require('assert'),path=require('path'),root=path.resolve(__dirname,'..'),cfg=require(root+'/core/config'),Game=require(root+'/core/game'),deps={};for(const[k,f]of Object.entries({World:'world',Entities:'entities',Progression:'progression',Save:'save'}))deps[k]=require(root+'/core/'+f);
function make(){const g=new Game(cfg,deps);g.setViewport(812,375);return g;}
let g=make();for(let i=0;i<160;i++)g.spawnTrialFoe(false,{x:100,y:100});assert.equal(g.foes.filter(f=>f.type==='spitter').length,0);
g=make();g.trial.killed=80;for(let i=0;i<160;i++)g.spawnTrialFoe(false,{x:100,y:100});assert.equal(g.foes.filter(f=>f.type==='spitter').length,1);g.advanceTrialWave();for(let i=0;i<210;i++)g.spawnTrialFoe(false,{x:100,y:100});assert.equal(g.foes.filter(f=>f.type==='spitter').length,2);g.wave=3;g.trial.spawned=0;for(let i=0;i<120;i++)g.spawnTrialFoe(false,{x:100,y:100});assert.equal(g.foes.filter(f=>f.type==='spitter').length,2);
g=make();let f=deps.Entities.makeFoe(cfg,'spitter',g.player.x+250,g.player.y,1,1);g.foes.push(f);f.shootT=0;g.updateSpitter(.1,f,250);assert.equal(g.hazards.length,1);const h=g.hazards[0],target=h.x;g.player.x+=100;g.updateSpitter(.5,f,250);assert(h.launched);assert.equal(h.x,target);assert(f.recovery>0);let hp=g.player.hp;g.player.x=target;g.updateHazards(.5);assert.equal(g.player.hp,hp);g.updateHazards(.51);assert.equal(g.player.hp,hp-7);g.updateHazards(2.1);assert.equal(g.hazards.length,0);
g=make();f=deps.Entities.makeFoe(cfg,'spitter',100,100,1,1);g.foes=[f,{kind:'boss',cast:'slam'}];f.shootT=0;g.updateSpitter(1,f,250);assert.equal(g.hazards.length,0);g.foes.pop();g.hazards=[{kind:'poison'},{kind:'poison'}];g.updateSpitter(1,f,250);assert.equal(g.hazards.length,2);
g.hazards=[];g.updateSpitter(1,f,250);const snap=JSON.parse(JSON.stringify(deps.Save.snapshot(g,true))),resumed=make();deps.Save.applyRun(resumed,snap);assert.deepEqual(resumed.hazards,g.hazards);assert.equal(resumed.spitSerial,g.spitSerial);f.hp=0;g.onFoeDeath(f);assert.equal(g.hazards.length,0);
assert.deepEqual(cfg.enemyTypes.charger.spd,[67.6,84.5]);
// Real collision: player and ordinary enemies can traverse the narrow center; bank blocks sideways movement.
g=make();for(const c of g.world.corridors){for(let n=-130;n<=130;n+=5)assert(g.world.isFree(c.x+c.ux*n,c.y+c.uy*n,28));assert(!g.world.isFree(c.x-c.uy*70,c.y+c.ux*70,15));
 g.player.x=c.x+c.ux*170;g.player.y=c.y+c.uy*170;g.player.inv=999;const mob=deps.Entities.makeFoe(cfg,'slime',c.x-c.ux*170,c.y-c.uy*170,1,1);g.foes=[mob];for(let i=0;i<600;i++)g.updateFoes(1/60);assert(Math.hypot(mob.x-g.player.x,mob.y-g.player.y)<60,'corridor traversal stuck');}
console.log('PASS: ranged spawn caps, boss deferral, locked warning, poison lifetime/damage/save, kill interrupt, hunter speed and narrow passage collision/traversal');
